### ISSUE TITLE
非常感谢您的分享，但是demo运行不了哦？

### ISSUE THREAD

**Issue by tungh** [pinqy520/react-native-webview-invoke#1]
非常感谢您的辛苦分享，但是demo运行不了哦？

**Comment by pinqy520** [comment]
@tungh 我试了是可以的。。有报什么错误吗？还是通信不生效？

**Comment by tungh** [comment]
npm install react-native-webview-invoke --save
用这个安装后，使用会出现安装的node_modules里面的native.js内容为
export * from './src/native'
然后找不到

如果直接使用dev下面的demo，会出现不通讯，下面web side 点不了

**Comment by pinqy520** [comment]
@tungh 

呃，不好意思我的问题。。。直接运行dev下的demo除了需要在外面`npm start`以外，还需要单独起一个命令行执行`npm run static`用来访问browser.js 。。。

我待会优化下，你可以先试试`npm run static`

**Comment by pinqy520** [comment]
`npm install`的问题已解决了。。是发布的时候没处理好。。

感谢反馈~！

**Comment by tungh** [comment]
invoke = createInvoke(() => this.webview)
这行报错
(0,_native2.default) is not a function.(In '(0,_native2.default)(function(){return _this.webview;})','(0,_native2.default)' is undefined)

dev里的demo依然无法通讯
Possible Unhandled Promise Rejection (id:_this.invoke.fn.set is not a function.(In'_this.invoke.fn.set(_this.state.value)','_this.invoke.fn.set' is undefined)

**Comment by pinqy520** [comment]
@tungh dev里的demo程序`npm run static`之后reload依然这样么？

<img width="480" alt="32165afa1aa5f6719045daa1ed8c5665" src="https://cloud.githubusercontent.com/assets/5719833/21139472/03878f28-c16e-11e6-8d2c-647be3195248.png">

我这是可以跑起来的。。。

第一个问题

> invoke = createInvoke(() => this.webview)

重新安装下现在是`0.2.2`，应该已经没问题了。。。

**Comment by tungh** [comment]
dev里的可以，就是npm安装后的不可以

**Comment by tungh** [comment]
我看了下，主要是html连接不上，当启动了本地的http服务后可以连上，但是browser在目录里查找或者把browser放在网络上都不行？

**Comment by pinqy520** [comment]
你说dev目录？。。。html里面需要引入`browser.js`，我的browser.js是通过`http-server`放到`localhost`的，方便开发的时候进行调试，所以你在dev目录运行的时候首先需要启动`npm run static`启动`http-server`服务。。。


你自己使用npm安装，现在应该也是没问题的，之前导出的方式错了，现在在最新的`0.2.2`版本修复了这个问题，你需要重新`npm install react-native-webview-invoke`安装一下（记得指定名字，不然npm判断不到新版本）。。。

**Comment by pinqy520** [comment]
我之后重新新建一个示例工程把。。。开发工程有点不太容易看明白。。。

**Comment by tungh** [comment]
en  谢谢  麻烦你了

**Comment by pinqy520** [comment]
@tungh 

考虑再三感觉没必要新建一个工程，我之前默认的使用localhost的browser.js改成了使用cdn上的。。我自己开发的时候改回localhost即可，现在直接运行xcode工程可以泡起来了。。

https://github.com/pinqy520/react-native-webview-invoke/tree/master/dev

非常感谢反馈~！！！！
