### ISSUE TITLE
请问Demo有最新的吗？

### ISSUE THREAD

**Issue by TrustTheBoy** [pinqy520/react-native-webview-invoke#11]
《1》我在真机上使用时调取RN 的封装的方法回馈很慢，例如调取我封装的拍照功能，就需要等个7，8秒
《2》文档上的写法和Demo的不一样咧
《3》RN怎样调取html的方法呢？

**Comment by pinqy520** [comment]
1. 慢是安卓还是iOS，我在公司项目中用到调起并不慢。。你可以打个log看下是到rn慢还是你调起native的方法慢？ 
2. 哪两种写法不一样？现在又Bind和fn两种写法。。都可以用，建议使用Bind。
3. html的方法？

**Comment by TrustTheBoy** [comment]
1.安卓慢，调用拍照时很慢
2.就是你github里的Demo和README.md里面的写法不一样
3.就是RN调用web里面的方法，并且给RN方法返回数据，web页面加载后RN调用web中的JS方法

**Comment by pinqy520** [comment]
1. RN调起拍照慢的话，和这个Hybrid库应该没关系
2. 具体哪里？能帮忙列出一下么？如果有问题，均已Demo为主，我晚上看下T-T。
3. 能举个栗子么？我理解都只要封装一下就行了。。。

**Comment by TrustTheBoy** [comment]
我的拍照用的是react-native-camera这个。请问你用的是什么呢？

**Comment by pinqy520** [comment]
以为原来的老app有拍照的功能，所以直接用的现成的，暴露接口给rn。。并没有用过第三方的库。。你可以单独用一下这个库，看看调起速度是不是慢。。
