### ISSUE TITLE
我把react native的fetch暴露给webview之后，在网页里面fetch得到的response.json成了undefined

### ISSUE THREAD

**Issue by iuhux** [pinqy520/react-native-webview-invoke#12]
![image](https://cloud.githubusercontent.com/assets/809213/23785324/2b7d209c-05a2-11e7-86b2-6672fbaa12c5.png)
![image](https://cloud.githubusercontent.com/assets/809213/23785330/3287905c-05a2-11e7-8a1b-682ef2eee851.png)

这里的response.headers.get和response.json都成为了undefined，请问这是什么问题呢?

**Comment by pinqy520** [comment]
json是返回值的方法（函数），目前不支持带函数过去。。

**Comment by iuhux** [comment]
OK，明白了
