### ISSUE TITLE
App端时，web可以执App暴露的方法，浏览器中没反应也不执行，try catch 捕获不到，如何判断如果暴露方法没执行则执行其他的方法

### ISSUE THREAD

**Issue by TrustTheBoy** [pinqy520/react-native-webview-invoke#15]

**Comment by pinqy520** [comment]
是单纯没执行还是执行报错？如果只是单纯判断没执行，可以用`invoke.fn['functionName'] === undefined` 判断看看对方有没有暴露某个方法给你

**Comment by TrustTheBoy** [comment]
@pinqy520 如果在浏览器中，就不会执行，在RN的webview中因为有这个暴露方法，所以会执行，
我就是问问在除Rn webview，其他的浏览器（chrome...）中，怎样去检测RN暴露的方法有没有执行？

**Comment by pinqy520** [comment]
也是一样的～你在网页的代码中不是引用了`react-native-webview-invoke/browser`么。它提供的invoke就有fn可以判断呀。。不管你是在哪个浏览器中。。如果是在非RN webview中，invoke.fn应该是一个`{}`。
