### ISSUE TITLE
Setting onMessage on a WebView overrides existing values of window.postMessage, but a previous value

### ISSUE THREAD

**Issue by TrustTheBoy** [pinqy520/react-native-webview-invoke#16]
看见[react-native](https://github.com/facebook/react-native/pull/10941) 的 pr也有人提交了，需要修改几个文件，但是这样不太方便呐，我没去修改，特来问问大神有没有什么解决方案？
![image](https://cloud.githubusercontent.com/assets/20201085/26301294/56391fd4-3f13-11e7-8ced-a6aa3dabd365.png)

**Comment by pinqy520** [comment]
删除 https://github.com/facebook/react-native/blob/master/React/Views/RCTWebView.m#L284-L292 这个就行了吧，也只是在dev的时候提示

**Comment by TrustTheBoy** [comment]
刚刚按照[这个](https://github.com/facebook/react-native/pull/12997/commits/34d5053d682ee2ec203b2f459832131e7d11ab3e)方案改动之后，
没法通信了。。。。。

**Comment by TrustTheBoy** [comment]
只在dev提示吗？如果是这样的话不改也行吧，删除的这个只是报错的提示。

**Comment by TrustTheBoy** [comment]
白折腾了😂 😂 😭 😭 😭 😭 😭

**Comment by pinqy520** [comment]
= =是不是删除就没问题了= =ios应该是没问题的。。你按照那个postMessageNative的方案改肯定没法通信的，因为我默认走的是postMessage   https://github.com/pinqy520/react-native-webview-invoke/blob/master/src/browser.js#L8

**Comment by TrustTheBoy** [comment]
那样的话我把browser这个文件中的postMessage命名更改为postMessageNative，应该也是也可以的把

**Comment by pinqy520** [comment]
嗯，但是你还不得按那个方案改么。。。
