### ISSUE TITLE
想问下，web端怎么引用这个组件呢？

### ISSUE THREAD

**Issue by Ariel08081214** [pinqy520/react-native-webview-invoke#19]
web端和Rn代码是分开的，web怎么引用呢？

**Comment by pinqy520** [comment]
``` javascript
import invoke from 'react-native-webview-invoke/browser'
```
或者
``` html
<script src="./node_modules/react-native-webview-invoke/dist/browser.umd.js"></script>
<script>
var invoke = window.WebViewInvoke
</script>
```
文档里有写

**Comment by Ariel08081214** [comment]
web是远程的，你意思是要把这个组件也放到web上？

**Comment by pinqy520** [comment]
基本用法里有说明，native和web都要引入一个模块， `react-native-webview-invoke/browser`是web的，`react-native-webview-invoke/native` 是rn

如果是打包工具的，就 采用上面的代码npm 安装完了之后引入模块。

如果是script引入的，就将`react-native-webview-invoke/dist/browser.umd.js`这个文件放到cdn或者啥地址script引入进去。。

**Comment by Ariel08081214** [comment]
喔，明白了，要把那个js单独拿出来放到web服务器上引用。谢谢！

**Comment by pinqy520** [comment]
嗯嗯～
