### ISSUE TITLE
运行案例无法通信，也没有任何报错 react native 0.39.2

### ISSUE THREAD

**Issue by TrustTheBoy** [pinqy520/react-native-webview-invoke#2]
首先感谢楼主的分享
 我的项目使用:
    react native 0.39.2,
    react-native-webview-invoke 0.2.2
    react: 15.4.1
我的问题是：运行案例画面显示没问题，就是无法通信，也没有报错，按钮也可以点击
我是直接拷贝你的文件到我的项目，html文件放在网络使用http链接，界面运行没有报任何错误，只是无法通信，
我将html放在本地localhost访问也无法通信

**Comment by pinqy520** [comment]
@TrustTheBoy 感谢反馈，我试一下这个版本，照理说这个版本应该还没有合入新的message实现。。。

**Comment by pinqy520** [comment]
@TrustTheBoy 我知道为什么了。

ios工程中，默认只支持https。。所以我将cdn地址都改成是https的就好了。。已经更新到项目文件了

**Comment by TrustTheBoy** [comment]
@pinqy520 感谢你的回答，目前我在两端都试了，还是无法通信调用，我是直接运行你的InvokeTest项目，index.html的代码直接复制到[>>](http://huiyong.f3322.net:23808/landing-craft/craftFiles/school/page/schoolMap.html)
webView 直接加载这个，请问是否需要配置其他什么嘛？

**Comment by pinqy520** [comment]
@TrustTheBoy 呃，你这个远端地址也是http的。。webview能访问到这个页面么？。。还是你已经设置了安全设置？

我刚刚在iOS和安卓上都试过了，不用做其他额外配置了。。都没啥问题。。InvokeTest。。webview直接`require('./index.html')`的（和代码里面一样）。。

<img width="879" alt="fa9074e83e5551004f151101e8b0e08c" src="https://cloud.githubusercontent.com/assets/5719833/21167815/100997b0-c1ea-11e6-9840-22bfe3aff871.png">

能否提供一下你的工程给我试试？

**Comment by TrustTheBoy** [comment]
@pinqy520 webview可以访问到这个页面，
我只改了下webview中的url
`export default class InvokeTest extends Component {
  webview: WebView
  invoke = createInvoke(() => this.webview)
  webInitialize = () => {
    alert('[Ready] Done!')
  }
  webWannaGet = () => 'Hi, Web!'
  webWannaSet = (data) => {
    alert(`[Receive From Web] '${data}'`)
  }
  componentDidMount() {
    this.invoke
      .define('init', this.webInitialize)
      .define('get', this.webWannaGet)
      .define('set', this.webWannaSet)
  }
  render() {
    return (
      <WebView ref={w => this.webview = w}
        source={{uri:'http://huiyong.f3322.net:23808/landing-craft/craftFiles/school/page/schoolMap.html'}}
        onMessage={this.invoke.listener}
        />
    );
  }
}`

**Comment by pinqy520** [comment]
呃。。。我刚刚在本地试了一下你的地址也是可以的。。。要不加QQ具体看下。。。

**Comment by TrustTheBoy** [comment]
@pinqy520 QQ:603049583

**Comment by pinqy520** [comment]
已修复，感谢反馈~！！！！
