### ISSUE TITLE
Web调用RN接口的时候，能把一个方法作为参数传递给RN吗？

### ISSUE THREAD

**Issue by Ariel08081214** [pinqy520/react-native-webview-invoke#20]
有个需求是这样的，web调用要rn接口改变header右侧的菜单按钮，每个菜单肯定都会有点击事件，我能把方法作为参数传过去，rn来调用这个方法吗？谢谢！

**Comment by pinqy520** [comment]
不支持，不太好支持。。应该有其他方法可以实现。。

**Comment by Ariel08081214** [comment]
喔，我感觉这种需求是通用的吧？如果能将方法传递过去，直接绑定到click事件中，好方便哦。

**Comment by pinqy520** [comment]
这个库本质是消息通信，只是将消息通信封装成类似函数调用的形式，并不是说rn和web真的直接互相调用了，所以支持的类型只是JSON支持的类型。 就算是函数调用，也只能说特殊类型判断，然后模拟成函数调用的形式，那样的话，除了函数，还有很多类，比如Date WebRTC的，随着需求增多是不是都需要模拟？那样就太重了，这个库主要是想用最轻量级的方法解决大部分问题，所以并没有支持更多类型的计划。

**Comment by Ariel08081214** [comment]
嗯，好的，我试试通过其他方式实现，谢谢！

**Comment by pinqy520** [comment]
嗯嗯^_^
