### ISSUE TITLE
invoke.bind  undefine 

### ISSUE THREAD

**Issue by hu8373551** [pinqy520/react-native-webview-invoke#21]
React  引入项目 后 
import invoke from 'react-native-webview-invoke/browser'

用invoke.bind 出现  _browser2.default.bind is not a function

**Comment by EliYenn** [comment]
我也遇到这个问题，不知道如何解决，webview是引用的vue项目

**Comment by sxa645899409** [comment]
@hu8373551 @15914038396 用invoke.default.bind就好了。

**Comment by pinqy520** [comment]
修复了，不好意思最近公司比较忙
