### ISSUE TITLE
iOS RN调用webView方法的一点问题

### ISSUE THREAD

**Issue by Dawninest** [pinqy520/react-native-webview-invoke#22]
感谢分享，
首先说明这并不算这个RN插件的问题，只是在使用这个插件的时候遇到的使用上的问题，
webView中绑定的方法最后会更改 window.location.href 原地刷新页面，
安卓版没有任何问题，
然而iOS版的话，不会自动去更新页面,
怀疑时iOS的WebView相关设定的问题，
有遇到过类型情况么？
非常感谢

**Comment by pinqy520** [comment]
你是说在iOS里调用 window.location.href 不会跳转么？

**Comment by Dawninest** [comment]
对，安卓没问题，只是iOS里面出现这个问题。
后续还发现：
如果window.location.href是由webView页面上的方法自己调用，就没有问题,
如果window.location.href是写到提供给RN调用的方法里面，就会出现不跳转没反应的情况。

**Comment by pinqy520** [comment]
你setTimeout试一试window.location.href能不能生效，如果可以，你看看是不是没吊用到那个方法，或者是不是报错了

**Comment by Dawninest** [comment]
能调到了这个方法，但是没有后续操作了，不光 window.location.href 不行，window.location.reload() 也不会执行，我怀疑这里是否会是因为绑定的问题导致这里调用时的 "window" 不是正确的应该用来操作的 "window"

**Comment by Dawninest** [comment]
window.location.href 放 setTimeout 里面能行了。。
这。。可真是匪夷所思啊。。
感谢解答🙏

**Comment by pinqy520** [comment]
不客气，改天我研究下，最近业务好久没用webview了
