### ISSUE TITLE
not worked in iframe

### ISSUE THREAD

**Issue by JustinWang23** [pinqy520/react-native-webview-invoke#23]
在iframe里加载invoke，调用native的方法不生效，是不是invoke.listener无法监听到iframe的window.postMessage方法

**Comment by JustinWang23** [comment]
已解决

**Comment by OzoraTsu** [comment]
@JustinWang23 请问是怎么解决的？

**Comment by JustinWang23** [comment]
> @JustinWang23 请问是怎么解决的？

@OzoraTsu iframe有自己的window对象，通过window.parent将invoke绑到外部页面的window对象上就可以了

**Comment by pinqy520** [comment]
赞
