### ISSUE TITLE
你好，请问我如何在web调用方法的时候传回掉函数呢？

### ISSUE THREAD

**Issue by TrustTheBoy** [pinqy520/react-native-webview-invoke#3]
你好，请问我如何在web调用方法的时候传回掉函数呢？

**Comment by pinqy520** [comment]
回调函数？执行函数返回的是一个Promise。。。await住或者.then就可以了

**Comment by TrustTheBoy** [comment]
@pinqy520 你好，你有时间上下QQ吗？我详细给你说下，已经困扰了半天了去
