### ISSUE TITLE
配合react-native-webview，Android6上面，不起作用了！

### ISSUE THREAD

**Issue by Ariel08081214** [pinqy520/react-native-webview-invoke#37]
Android7+都是对的，能够双方传递数据，Android6上面就不行了
去掉本库，用普通的window.ReactNativeWebView.postMessage和onMessage就可以，麻烦能修复下这个问题嘛？

**Comment by Ariel08081214** [comment]
React Native:0.61
react-native-webview:9.1.1

**Comment by pinqy520** [comment]
应该是箭头函数的问题，安装最新版试试
