### ISSUE TITLE
升级之后  接受参数变成arr了？

### ISSUE THREAD

**Issue by toby-lei** [pinqy520/react-native-webview-invoke#38]

**Comment by pinqy520** [comment]
并没有变动，是声明的问题还是调用的问题？有例子吗

**Comment by ray-toby** [comment]
@pinqy520 
![image](https://user-images.githubusercontent.com/19220426/83863396-dcff5080-a755-11ea-81a8-43a1bdbb044e.png)
![image](https://user-images.githubusercontent.com/19220426/83863437-e8eb1280-a755-11ea-8b67-d1a5f3ffce82.png)传的object   接受的被[]包裹起来了

**Comment by pinqy520** [comment]
0.6.2 修复了

**Comment by pinqy520** [comment]
如果没有问题了我先关闭了，如果还是有问题，可以再打开这个Issue哈
