### ISSUE TITLE
请问这个对系统最低的版本要求是什么？ios和安卓，我用安卓4.3不可以

### ISSUE THREAD

**Issue by TrustTheBoy** [pinqy520/react-native-webview-invoke#4]
请问这个对系统最低的版本要求是什么？ios和安卓，我用安卓4.3不可以

**Comment by pinqy520** [comment]
@TrustTheBoy 官方实现用了`new MessageEvent`，在安卓4.3 ~ 4.1是不支持的。。我已经提交了一个PR: https://github.com/facebook/react-native/pull/11560 。。不知道RN修不修。。所以目前版本只能支持4.4以上了。。

**Comment by TrustTheBoy** [comment]
@pinqy520 好的，非常感谢

**Comment by pinqy520** [comment]
PR已经合并到主干了，下一个发布版本应该就能修复了
