### ISSUE TITLE
ios release 版本rn发消息到web，web接收不到，请问怎么回事呢？

### ISSUE THREAD

**Issue by dongsuju** [pinqy520/react-native-webview-invoke#7]
ios的debug 、 Android 的debug 和release都正常

**Comment by pinqy520** [comment]
我在我的dev工程中试了一下release模式是没问题的。。理论上说，这个库是纯Js写的，是不可能因为native的设置而有影响。。你可以单纯用官方的接口尝试一下postMessage看看其是否生效。

**Comment by dongsuju** [comment]
postMessage 也存在相同问题

**Comment by dongsuju** [comment]
我的qq：2730589541，方便的话 加个qq沟通一下吧，release版本的问题 很不容易发现

**Comment by pinqy520** [comment]
@dongsuju 你的要验证问题，我的2478700724 你加我的吧
